apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduler-plugin-extra
rules:
- apiGroups: [""]
  resources: ["pods/binding"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch", "update"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler-plugin-extra-binding
subjects:
- kind: ServiceAccount
  name: scheduler-plugin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: scheduler-plugin-extra
  apiGroup: rbac.authorization.k8s.io