apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: db-service-scaledobj
  labels:
    app: db-service
spec:
  scaleTargetRef:
    kind: Deployment
    name: db-service
    
  minReplicaCount: 2
  maxReplicaCount: 6
  
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "50" # Worker xử lý Message tốn CPU, 50% là ngưỡng đẹp
  
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      behavior:
        # Ngâm tải lâu hơn API (5 phút), đảm bảo Database Worker cày hết Hàng đợi NATS
        scaleDown:
          stabilizationWindowSeconds: 300 
          policies:
          - type: Pods
            value: 1
            periodSeconds: 60
          selectPolicy: Min
        
        # SCALE UP THEO KIỂU PHẢN ỨNG NHANH
        scaleUp:
          stabilizationWindowSeconds: 0 # Xóa bỏ thời gian chờ 30s chết người!
          policies:
          - type: Pods
            value: 2                    # Đẻ ra 2 worker mỗi 15s để bào queue
            periodSeconds: 15
          - type: Percent
            value: 100
            periodSeconds: 15
          selectPolicy: Max