apiVersion: v1
kind: Service
metadata:
  name: api-services
  namespace: default
spec:
  selector:
    app: api-services
  ports:
  - name: api-services
    protocol: TCP
    port: 4000
    targetPort: 4000
  type: ClusterIP
