apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-services
spec:
  replicas: 2  # minReplicaCount từ KEDA ScaledObject
  selector:
    matchLabels:
      app: api-services
  template:
    metadata:
      labels:
        app: api-services
    spec:
      # schedulerName:  my-scheduler
      containers:
      - name: api-services
        image: shieldxbot/go-api-services:v1.0.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: REDIS_WRITE_ADDR
          value: "192.168.0.5:6379"
        - name: REDIS_READ_ADDRS
          value: "192.168.0.5:6379 ,192.168.0.5:6379"
        - name: NATS_SERVERS
          value: "nats://192.168.0.4:2222,nats://192.168.0.7:5222,nats://192.168.0.8:6222"
        - name: NATS_TIMEOUT
          value: "8s"
        - name: CACHE_TTL
          value: "600s"
        - name: SERVER_PORT
          value: ":4000"
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "106Mi"
            cpu: "100m"
   