apiVersion: v1
kind: ConfigMap
metadata:
  name: methods-config
  namespace: course-reg-exp
data:
  M1: |
    {
      "queue_enabled": false,
      "rule_engine": false,
      "topsis": false,
      "optimizer": "fcfs"
    }
  M2: |
    {
      "queue_enabled": false,
      "rule_engine": false,
      "topsis": false,
      "time_window_per_year": true
    }
  M3: |
    {
      "queue_enabled": true,
      "rule_engine": true,
      "topsis": false,
      "priority_formula": "year*10 + credits_missing"
    }
  M4: |
    {
      "queue_enabled": true,
      "rule_engine": true,
      "topsis": true,
      "optimizer": "topsis_ilp"
    }